# Use official Python image
FROM python:3.12-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Collect static files if needed (adjust to your config)
RUN python manage.py collectstatic --noinput

# Expose port 8000
EXPOSE 8000

# Run Gunicorn server for Django app
CMD ["gunicorn", "stormDRFBackend.wsgi:application", "--bind", "0.0.0.0:8000"]
