# Generated by Django 5.2.1 on 2025-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FLOOD', 'Flood'), ('RAINFALL', 'Heavy Rainfall'), ('WATER_LEVEL', 'Water Level Spike'), ('BLOCKAGE', 'Drainage Blockage'), ('TYPHOON', 'Typhoon Warning')], max_length=20)),
                ('source', models.CharField(choices=[('IOT', 'IoT Sensor'), ('PINN', 'Physics-Informed NN'), ('ML', 'Machine Learning Model'), ('NWP', 'Numerical Weather Prediction'), ('OWA', 'OpenWeatherAPI'), ('USER', 'Crowdsourced Report')], max_length=10)),
                ('severity', models.FloatField(help_text='Scale from 0 (low) to 1 (critical)')),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alert_images/')),
                ('reporter_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
